# configuration for VSCode graphql extension
# Schema URL should match your environment configuration
# Update this to match your actual backend URL
schema: "./schema.graphql"  # Local schema file for build and development
documents: "**/*.{graphql,gql,js,ts,jsx,tsx}"
