query getPostReports($resolvedOnly: Boolean, $limit: Int) {
  getPostReports(resolvedOnly: $resolvedOnly, limit: $limit) {
    id
    reason
    resolved
    creationDate
    creatorId
    postId
    originalPostTitle
    originalPostBody
    originalPostUrl
  }
}