query listBannedUsers($page: Int, $limit: Int) {
  listBannedUsers(page: $page, limit: $limit) {
    persons {
      id
      name
      displayName
      avatar
      isAdmin
      isBanned
      creationDate
    }
    totalCount
  }
}
