query listRegistrationApplications($limit: Int, $offset: Int) {
  listRegistrationApplications(limit: $limit, offset: $offset) {
    id
    userId
    username
    answer
    adminId
    denyReason
    creationDate
  }
}

query getRegistrationApplication($applicationId: Int!) {
  getRegistrationApplication(applicationId: $applicationId) {
    id
    userId
    username
    answer
    adminId
    denyReason
    creationDate
  }
}

query registrationApplicationsCount {
  registrationApplicationsCount
}