query getBoardModerators($boardId: Int!) {
  getBoardModerators(boardId: $boardId) {
    moderators {
      id
      person {
        id
        name
        display_name
        avatar
      }
      permissions
      created
    }
  }
}