query getMe {
  me {
    id
    name
    displayName
    avatar
    banner
    bio
    bioHTML
    isAdmin
    isDeleted
    isBanned
    unbanDate
    creationDate
    updated
    rep
    postCount
    commentCount
    postScore
    commentScore
    hasVerifiedEmail
    adminLevel
    profileBackground
    profileMusic
    profileMusicYoutube
    isApplicationAccepted
    isLocal
    instance
    settings {
      showNSFW
    }
    joinedBoards {
      id
      name
      title
      icon
    }
    moderates {
      board {
        id
        name
        title
        icon
      }
    }
  }
  unreadRepliesCount
  unreadMentionsCount
}