query listInvites($page: Int, $limit: Int) {
  listInvites(page: $page, limit: $limit) {
    invites {
      id
      verification_code
      created
      expires
      used
      creator {
        id
        name
        display_name
      }
    }
    total_count
  }
}