query listBannedUsers($page: Int, $limit: Int) {
  listBannedUsers(page: $page, limit: $limit) {
    persons {
      person {
        id
        name
        display_name
        avatar
        creation_date
        is_banned
        unban_date
        ban_reason
      }
    }
    total_count
  }
}