enum SortType {
  active,
  hot,
  new,
  old,
  topDay,
  topWeek,
  topMonth,
  topYear,
  topAll,
  mostComments,
  newComments
}

enum CommentSortType {
  hot
  top
  new
  old
}

query userProfile(
  $username: String!
  $sort: SortType
  $page: Int
  $limit: Int
  $includeBoard: Boolean!
  $withPosts: Boolean!
  $withComments: Boolean!
) {
  user(name: $username) {
    id
    name
    displayName
    avatar
    banner
    profileBackground
    bio
    bioHTML
    creationDate
    isAdmin
    adminLevel
    postCount
    commentCount
    postScore
    commentScore
    rep
    posts(limit: $limit, sort: $sort, page: $page) @include(if: $withPosts) {
      id
      titleChunk
      title
      url
      bodyHTML
      isRemoved
      isDeleted
      isLocked
      isNSFW
      featuredBoard
      featuredLocal
      score
      myVote
      commentCount
      creationDate
      updated
      myModPermissions
      creator {
        id
        name
        instance
        adminLevel
        displayName
        avatar
      }
      board @include(if: $includeBoard) {
        id
        name
        title
        icon
        primaryColor
      }
    }
    comments(limit: $limit, page: $page)
      @include(if: $withComments) {
      id
      postId
      body
      bodyHTML
      isRemoved
      isLocked
      isDeleted
      creationDate
      updated
      score
      upvotes
      downvotes
      myVote
      isSaved
      level
      post {
        id
        title
        titleChunk
        isDeleted
      }
      board @include(if: $includeBoard) {
        name
        title
      }
      creator {
        name
        displayName
        instance
        isAdmin
        avatar
      }
    }
    moderates @include(if: $includeBoard) {
      board {
        name
        title
        icon
        subscribers
      }
    }
  }
}

