query getBoardModerators($boardId: Int!) {
  getBoardModerators(boardId: $boardId) {
    id
    boardId
    userId
    user {
      name
      displayName
      avatar
      isAdmin
    }
    creationDate
    permissions
    rank
    inviteAccepted
    inviteAcceptedDate
  }
}
