query getBoardBannedUsers($boardId: Int!, $limit: Int, $page: Int) {
  getBoardBannedUsers(boardId: $boardId, limit: $limit, page: $page) {
    totalCount
    bans {
      id
      boardId
      userId
      reason
      expires
      creationDate
      user {
        id
        name
        displayName
        avatar
        banner
        bio
        creationDate
        isAdmin
        isBanned
        unbanDate
      }
    }
  }
}