query getBoardSettings($boardId: Int!) {
  getBoardSettings(boardId: $boardId) {
    id
    name
    title
    description
    icon
    banner
    isNSFW
    creationDate
    updated
    isRemoved
    isBanned
    banReason
    publicBanReason
    bannedBy
    bannedAt
    primaryColor
    secondaryColor
    hoverColor
    sidebar
    sidebarHTML
    isHidden
    excludeFromAll
    postCount
    subscribers
    commentCount
    usersActiveDay
    usersActiveWeek
    usersActiveMonth
    usersActiveHalfYear
    myModPermissions
    subscribedType
  }
}