enum SortType {
  active
  hot
  new
  old
  topDay
  topWeek
  topMonth
  topYear
  topAll
  mostComments
  newComments
}

enum ListingType {
  all
  subscribed
  local
  moderated
}

query listBoards(
  $sort: SortType
  $page: Int
  $limit: Int
  $searchTerm: String
  $listingType: ListingType
  $searchTitleAndDesc: Boolean
  $bannedBoards: Boolean
) {
  listBoards(
    sort: $sort
    page: $page
    limit: $limit
    searchTerm: $searchTerm
    listingType: $listingType
    searchTitleAndDesc: $searchTitleAndDesc
    bannedBoards: $bannedBoards
  ) {
    id
    name
    title
    description
    creationDate
    updated
    isDeleted
    isNSFW
    isHidden
    icon
    banner
    isRemoved
    banReason
    primaryColor
    secondaryColor
    hoverColor
    sidebar
    sidebarHTML
    isBanned
    publicBanReason
    bannedBy
    bannedAt
    excludeFromAll
    subscribers
    postCount
    commentCount
    usersActiveDay
    usersActiveWeek
    usersActiveMonth
    usersActiveHalfYear
    subscribedType
    myModPermissions
    moderators {
      user {
        id
        name
        displayName
        avatar
      }
    }
  }
}