enum UserSortType {
  new
  old
  mostRep
  mostPosts
  mostComments
}

enum UserListingType {
  all
  admins
  banned
}

query listMembers(
  $page: Int, 
  $limit: Int, 
  $sort: UserSortType, 
  $searchTerm: String,
  $listingType: UserListingType
) {
  listUsers(
    page: $page, 
    limit: $limit, 
    sort: $sort, 
    searchTerm: $searchTerm,
    listingType: $listingType
  ) {
    id
    name
    displayName
    avatar
    adminLevel
    instance
    creationDate
    rep
    postCount
    commentCount
    isBanned
    isDeleted
    unbanDate
    bio
    profileBackground
    banner
  }
}