query getNotifications {
  getNotifications {
    id
    kind
    isRead
    created
    comment {
      id
      body
      creationDate
      creator {
        name
        displayName
        avatar
      }
      post {
        id
        title
      }
    }
    post {
      id
      title
      body
      creationDate
      creator {
        name
        displayName
        avatar
      }
      board {
        name
        title
      }
    }
  }
}
