query {
  me {
    id
    name
    displayName
    isBanned
    unbanDate
    avatar
    adminLevel
    rep
    postScore
    commentScore
    creationDate
    postCount
    commentCount
    joinedBoards {
      icon
      name
      title
      subscribers
    }
    moderates {
      board {
        icon
        name
        title
        subscribers
      }
    }
  }
  unreadRepliesCount
  unreadMentionsCount
}