query getEmoji($emojiId: Int!) {
  getEmoji(emojiId: $emojiId) {
    id
    shortcode
    imageUrl
    altText
    category
    creationDate
    updated
    boardId
    createdByUserId
    isActive
    usageCount
    emojiScope
  }
}